// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: OLED

#ifndef _OLED_UI_H
#define _OLED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Bahnschrit);
LV_FONT_DECLARE(ui_font_Bahnschrit);
LV_FONT_DECLARE(ui_font_Bahnschrit24);
LV_FONT_DECLARE(ui_font_Bahnschrit48);
LV_FONT_DECLARE(ui_font_Bahnschrift48);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
