// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: OLED

#ifndef _OLED_UI_H
#define _OLED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void movedown_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel;
extern lv_obj_t * ui_lbl_intensity;
extern lv_obj_t * ui_img_intensity_00;
extern lv_obj_t * ui_img_intensity_01;
extern lv_obj_t * ui_img_intensity_02;
extern lv_obj_t * ui_img_intensity_03;
extern lv_obj_t * ui_img_intensity_04;
extern lv_obj_t * ui_lbl_color;
extern lv_obj_t * ui_img_color_00;
extern lv_obj_t * ui_img_color_01;
extern lv_obj_t * ui_img_color_02;
extern lv_obj_t * ui_img_color_03;
extern lv_obj_t * ui_lbl_timer;
extern lv_obj_t * ui_img_timer_00;
extern lv_obj_t * ui_img_timer_01;
extern lv_obj_t * ui_img_timer_02;
extern lv_obj_t * ui_img_timer_03;
extern lv_obj_t * ui_img_timer_04;
extern lv_obj_t * ui_lbl_display;
extern lv_obj_t * ui_img_display_01;
extern lv_obj_t * ui_img_display_02;
extern lv_obj_t * ui_img_display_03;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_open_circle_png);    // assets/open_circle.png
LV_IMG_DECLARE(ui_img_closed_circle_png);    // assets/closed_circle.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
