// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: OLED

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Panel);
    lv_obj_set_width(ui_Panel, 128);
    lv_obj_set_height(ui_Panel, 128);
    lv_obj_set_x(ui_Panel, -1);
    lv_obj_set_y(ui_Panel, -64);
    lv_obj_clear_flag(ui_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_intensity = lv_label_create(ui_Panel);
    lv_obj_set_width(ui_lbl_intensity, 78);
    lv_obj_set_height(ui_lbl_intensity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_intensity, 0);
    lv_obj_set_y(ui_lbl_intensity, 64);
    lv_label_set_long_mode(ui_lbl_intensity, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lbl_intensity, "Intensity");
    lv_obj_set_style_text_font(ui_lbl_intensity, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_intensity_00 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_intensity_00, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_intensity_00, 10);
    lv_obj_set_height(ui_img_intensity_00, 16);
    lv_obj_set_x(ui_img_intensity_00, 70);
    lv_obj_set_y(ui_img_intensity_00, 64);
    lv_obj_add_flag(ui_img_intensity_00, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_intensity_00, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_intensity_01 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_intensity_01, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_intensity_01, 10);
    lv_obj_set_height(ui_img_intensity_01, 16);
    lv_obj_set_x(ui_img_intensity_01, 80);
    lv_obj_set_y(ui_img_intensity_01, 64);
    lv_obj_add_flag(ui_img_intensity_01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_intensity_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_intensity_02 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_intensity_02, &ui_img_closed_circle_png);
    lv_obj_set_width(ui_img_intensity_02, 10);
    lv_obj_set_height(ui_img_intensity_02, 16);
    lv_obj_set_x(ui_img_intensity_02, 90);
    lv_obj_set_y(ui_img_intensity_02, 64);
    lv_obj_add_flag(ui_img_intensity_02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_intensity_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_intensity_03 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_intensity_03, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_intensity_03, 10);
    lv_obj_set_height(ui_img_intensity_03, 16);
    lv_obj_set_x(ui_img_intensity_03, 100);
    lv_obj_set_y(ui_img_intensity_03, 64);
    lv_obj_add_flag(ui_img_intensity_03, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_intensity_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_intensity_04 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_intensity_04, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_intensity_04, 10);
    lv_obj_set_height(ui_img_intensity_04, 16);
    lv_obj_set_x(ui_img_intensity_04, 110);
    lv_obj_set_y(ui_img_intensity_04, 64);
    lv_obj_add_flag(ui_img_intensity_04, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_intensity_04, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_color = lv_label_create(ui_Panel);
    lv_obj_set_width(ui_lbl_color, 78);
    lv_obj_set_height(ui_lbl_color, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_color, 0);
    lv_obj_set_y(ui_lbl_color, 80);
    lv_label_set_text(ui_lbl_color, "Color");
    lv_obj_set_style_text_font(ui_lbl_color, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_color_00 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_color_00, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_color_00, 10);
    lv_obj_set_height(ui_img_color_00, 16);
    lv_obj_set_x(ui_img_color_00, 70);
    lv_obj_set_y(ui_img_color_00, 80);
    lv_obj_add_flag(ui_img_color_00, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_color_00, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_color_01 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_color_01, &ui_img_closed_circle_png);
    lv_obj_set_width(ui_img_color_01, 10);
    lv_obj_set_height(ui_img_color_01, 16);
    lv_obj_set_x(ui_img_color_01, 80);
    lv_obj_set_y(ui_img_color_01, 80);
    lv_obj_add_flag(ui_img_color_01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_color_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_color_02 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_color_02, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_color_02, 10);
    lv_obj_set_height(ui_img_color_02, 16);
    lv_obj_set_x(ui_img_color_02, 90);
    lv_obj_set_y(ui_img_color_02, 80);
    lv_obj_add_flag(ui_img_color_02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_color_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_color_03 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_color_03, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_color_03, 10);
    lv_obj_set_height(ui_img_color_03, 16);
    lv_obj_set_x(ui_img_color_03, 100);
    lv_obj_set_y(ui_img_color_03, 80);
    lv_obj_add_flag(ui_img_color_03, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_color_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_timer = lv_label_create(ui_Panel);
    lv_obj_set_width(ui_lbl_timer, 78);
    lv_obj_set_height(ui_lbl_timer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_timer, 0);
    lv_obj_set_y(ui_lbl_timer, 96);
    lv_label_set_text(ui_lbl_timer, "Timer");
    lv_obj_set_style_text_font(ui_lbl_timer, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_timer_00 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_timer_00, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_timer_00, 10);
    lv_obj_set_height(ui_img_timer_00, 16);
    lv_obj_set_x(ui_img_timer_00, 70);
    lv_obj_set_y(ui_img_timer_00, 96);
    lv_obj_add_flag(ui_img_timer_00, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_timer_00, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_timer_01 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_timer_01, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_timer_01, 10);
    lv_obj_set_height(ui_img_timer_01, 16);
    lv_obj_set_x(ui_img_timer_01, 80);
    lv_obj_set_y(ui_img_timer_01, 96);
    lv_obj_add_flag(ui_img_timer_01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_timer_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_timer_02 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_timer_02, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_timer_02, 10);
    lv_obj_set_height(ui_img_timer_02, 16);
    lv_obj_set_x(ui_img_timer_02, 90);
    lv_obj_set_y(ui_img_timer_02, 96);
    lv_obj_add_flag(ui_img_timer_02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_timer_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_timer_03 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_timer_03, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_timer_03, 10);
    lv_obj_set_height(ui_img_timer_03, 16);
    lv_obj_set_x(ui_img_timer_03, 100);
    lv_obj_set_y(ui_img_timer_03, 96);
    lv_obj_add_flag(ui_img_timer_03, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_timer_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_timer_04 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_timer_04, &ui_img_closed_circle_png);
    lv_obj_set_width(ui_img_timer_04, 10);
    lv_obj_set_height(ui_img_timer_04, 16);
    lv_obj_set_x(ui_img_timer_04, 110);
    lv_obj_set_y(ui_img_timer_04, 96);
    lv_obj_add_flag(ui_img_timer_04, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_timer_04, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_display = lv_label_create(ui_Panel);
    lv_obj_set_width(ui_lbl_display, 78);
    lv_obj_set_height(ui_lbl_display, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_display, 0);
    lv_obj_set_y(ui_lbl_display, 112);
    lv_label_set_text(ui_lbl_display, "Display");
    lv_obj_set_style_text_font(ui_lbl_display, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_display_01 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_display_01, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_display_01, 10);
    lv_obj_set_height(ui_img_display_01, 16);
    lv_obj_set_x(ui_img_display_01, 70);
    lv_obj_set_y(ui_img_display_01, 112);
    lv_obj_add_flag(ui_img_display_01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_display_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_display_02 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_display_02, &ui_img_open_circle_png);
    lv_obj_set_width(ui_img_display_02, 10);
    lv_obj_set_height(ui_img_display_02, 16);
    lv_obj_set_x(ui_img_display_02, 80);
    lv_obj_set_y(ui_img_display_02, 112);
    lv_obj_add_flag(ui_img_display_02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_display_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_display_03 = lv_img_create(ui_Panel);
    lv_img_set_src(ui_img_display_03, &ui_img_closed_circle_png);
    lv_obj_set_width(ui_img_display_03, 10);
    lv_obj_set_height(ui_img_display_03, 16);
    lv_obj_set_x(ui_img_display_03, 90);
    lv_obj_set_y(ui_img_display_03, 112);
    lv_obj_add_flag(ui_img_display_03, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_display_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
